name: Wait all checks

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  workflow_call:

jobs:
  wait-all-checks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: Wait all GitHub checks
        uses: poseidon/wait-for-status-checks@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore: "wait-all-checks / wait-all-checks"
